name: TEST - Save Maven Build Scan

on:
  pull_request:

jobs:
  create-and-save-build-scans:
    name: Create and Save Build Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Checkout Maven sample project
        uses: actions/checkout@v4
        with:
          repository: 'gradle/gradle-enterprise-build-config-samples'
          path: 'sample'
          ref: 'main'
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Save Maven Build Scan (no-op)
        uses: ./maven/build-scan/save
      - name: Run Maven Build 1
        working-directory: ./sample/common-gradle-enterprise-maven-configuration
        run: mvn clean -B
      - name: Save Maven Build Scan 1
        uses: ./maven/build-scan/save
      - name: Run Maven Build 2
        working-directory: ./sample/common-gradle-enterprise-maven-configuration
        run: mvn initialize -B
      - name: Save Maven Build Scan 2
        uses: ./maven/build-scan/save

  check-saved-build-scans:
    name: Verify Saved Build Scans
    needs: create-and-save-build-scans
    runs-on: ubuntu-latest
    env:
      DATA_ARTIFACT_NAME: 'maven-build-scan-data'
      METADATA_ARTIFACT_NAME: 'maven-build-scan-metadata'
    steps:
      - name: Download data workflow artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.DATA_ARTIFACT_NAME }}
          path: ${{ env.DATA_ARTIFACT_NAME }}
      - name: Verify Build Scan count
        run: |
          scanCount=$(find ${{ env.DATA_ARTIFACT_NAME }} -type f -name 'scan.scan' | wc -l)
          if [ "$scanCount" != "2" ]; then
            echo "Found $scanCount scans (2 expected)"
            exit 1
          fi
      - name: Download metadata workflow artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.METADATA_ARTIFACT_NAME }}
          path: ${{ env.METADATA_ARTIFACT_NAME }}
      - name: Verify metadata files count
        run: |
          metadataFilesCount=$(find ${{ env.METADATA_ARTIFACT_NAME }} -type f -name '*-ge-extension-versions.txt' | wc -l)
          if [ "$metadataFilesCount" != "2" ]; then
            echo "Found $metadataFilesCount metadata files (2 expected)"
            exit 1
          fi
